version: 2

registries:
  flexcompute-codeartifact:
    type: python-index
    url: https://flexcompute-625554095313.d.codeartifact.us-east-1.amazonaws.com/pypi/pypi-releases/simple/
    aws-region: us-east-1
    account-id: '625554095313'
    role-name: github-dependabot-tidy3d-codeartifact-prod-aws
    domain: flexcompute
    domain-owner: '625554095313'

updates:

  - package-ecosystem: "pip"
    directory: "/"   # folder containing pyproject.toml + poetry.lock
    registries:
      - flexcompute-codeartifact
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      semver-patch-days: 7
      semver-minor-days: 7
      semver-major-days: 30
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
    groups:
      python:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      # Minimum age (in days) required for any new dependency release before Dependabot will open an update PR.
      # Security updates are not delayed by cooldown.
      default-days: 7
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions:
        patterns:
          - "*"
