minimum_pre_commit_version: '4.0.0'
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: local
    hooks:
      - id: move-type-imports
        name: move type-only imports under TYPE_CHECKING
        entry: poetry run python scripts/move_type_imports.py --mode fix --only-changed
        language: system
        pass_filenames: false
        stages: [pre-commit]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.11"
    hooks:
     - id: ruff-check
       args: [ --fix ]
       stages: [pre-commit]
     - id: ruff-format
       stages: [pre-commit]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.22.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        verbose: true
        entry: bash -c 'commitlint --edit || exit 0'
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    # Zizmor version.
    rev: v1.19.0
    hooks:
      - id: zizmor
        stages: [pre-commit]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: mypy (type signatures)
        pass_filenames: false
        args:
          - --config-file=pyproject.toml
