repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.11"
    hooks:
     - id: ruff
       args: [ --fix ]
     - id: ruff-format
  - repo: local
    hooks:
      - id: test_local
        name: Run tests with coverage
        entry: scripts/test_local.sh
        language: system
        pass_filenames: false
        stages: [manual]
        verbose: true
