version: 2

submodules:
  include:
    - docs/notebooks
  recursive: true

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
sphinx:
  fail_on_warning: false
  configuration: docs/conf.py
  
python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev

formats: []

# Build from the docs/ directory with Sphinx
# sphinx:
#   configuration: docs/conf.py
#
#   # Explicitly set the version of Python and its requirements
#   python:
#     install:
#         - requirements: docs/requirements.txt
