"""Grid-spec entities helpers."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from tidy3d.components.structure import Structure

if TYPE_CHECKING:
    from pydantic import PositiveFloat

    from tidy3d.components.grid.grid_spec.constants import CornersAndConvexity
    from tidy3d.components.lumped_element import LumpedElementType
    from tidy3d.components.structure import MeshOverrideStructure, StructureType
    from tidy3d.components.types import CoordinateOptional, PriorityMode, Shapely

    from .model import GridSpec


def snapping_points_used(self: GridSpec) -> tuple[bool, bool, bool]:
    """Along each axis, ``True`` if any snapping point is used. However,
    it is still ``False`` if all snapping points take value ``None`` along the axis.
    """

    # empty list
    if not self.snapping_points:
        return False, False, False

    x_used = any(p[0] is not None for p in self.snapping_points)
    y_used = any(p[1] is not None for p in self.snapping_points)
    z_used = any(p[2] is not None for p in self.snapping_points)

    return x_used, y_used, z_used


def override_structures_used(self: GridSpec) -> tuple[bool, bool, bool]:
    """Along each axis, ``True`` if any override structure is used. However,
    it is still ``False`` if only :class:`.MeshOverrideStructure` is supplied, and
    their ``dl[axis]`` all take the ``None`` value.
    """

    # empty override_structure list
    if len(self.override_structures) == 0:
        return False, False, False

    override_used = [False] * 3
    for structure in self.override_structures:
        # override used in all axes if any `Structure` is present
        if isinstance(structure, Structure):
            return True, True, True

        for dl_axis, dl in enumerate(structure._dl):
            if (not override_used[dl_axis]) and (dl is not None):
                override_used[dl_axis] = True
    return tuple(override_used)


def internal_snapping_points(
    self: GridSpec,
    structures: list[Structure],
    lumped_elements: list[LumpedElementType],
    boundary_types: tuple[tuple[str, str], tuple[str, str], tuple[str, str]],
    sim_bounds: tuple,
    cached_corners_and_convexity: list[CornersAndConvexity] | None = None,
    cached_merged_geos: list[tuple[Any, Shapely]] | None = None,
) -> list[CoordinateOptional]:
    """Internal snapping points. So far, internal snapping points are generated by
    `layer_refinement_specs` and lumped element.

    Parameters
    ----------
    structures : list[Structure]
        List of physical structures.
    lumped_elements : list[LumpedElementType]
        List of lumped elements.
    boundary_types : tuple[tuple[str, str], tuple[str, str], tuple[str, str]]
        Boundary type of the simulation domain.
    cached_corners_and_convexity : Optional[list[CornersAndConvexity]]
        Cached corners and convexity data.
    cached_merged_geos : Optional[list[list[tuple[Any, Shapely]]]]
        Cached merged geometries for each layer. If None, will be computed.
    sim_bounds : tuple
        Bounds of the simulation domain excluding the PML regions.

    Returns
    -------
    list[CoordinateOptional]
        List of snapping points coordinates.
    """

    # no need to generate anything if autogrid is not used
    if not self.auto_grid_used:
        return []

    snapping_points = []
    # 1) from layer refinement spec
    if self.layer_refinement_used:
        for ind, layer_spec in enumerate(self.layer_refinement_specs):
            if cached_corners_and_convexity is not None:
                cached_data = cached_corners_and_convexity[ind]
            else:
                cached_data = None
            if cached_merged_geos is not None:
                cached_merged = cached_merged_geos[ind]
            else:
                cached_merged = None
            snapping_points += layer_spec.generate_snapping_points(
                list(structures),
                sim_bounds,
                boundary_types,
                cached_data,
                cached_merged,
            )
    # ) from lumped_elements
    for lumped_element in lumped_elements:
        snapping_points += lumped_element.to_snapping_points()
    return snapping_points


def all_snapping_points(
    self: GridSpec,
    structures: list[Structure],
    lumped_elements: list[LumpedElementType],
    boundary_types: tuple[tuple[str, str], tuple[str, str], tuple[str, str]],
    sim_bounds: tuple,
    internal_snapping_points: list[CoordinateOptional] | None = None,
) -> list[CoordinateOptional]:
    """Internal and external snapping points. External snapping points take higher priority.
    So far, internal snapping points are generated by `layer_refinement_specs`.

    Parameters
    ----------
    structures : list[Structure]
        List of physical structures.
    lumped_elements : list[LumpedElementType]
        List of lumped elements.
    boundary_types : tuple[tuple[str, str], tuple[str, str], tuple[str, str]]
        Boundary type of the simulation domain.
    internal_snapping_points : list[CoordinateOptional]
        If `None`, recomputes internal snapping points.

    Returns
    -------
    list[CoordinateOptional]
        List of snapping points coordinates.
    """

    if internal_snapping_points is None:
        return self.internal_snapping_points(
            structures,
            lumped_elements,
            boundary_types,
            sim_bounds,
        ) + list(self.snapping_points)
    return internal_snapping_points + list(self.snapping_points)


def external_override_structures(self: GridSpec) -> list[StructureType]:
    """External supplied override structure list."""
    return [s.to_static() for s in self.override_structures]


def internal_override_structures(
    self: GridSpec,
    structures: list[Structure],
    wavelength: PositiveFloat,
    sim_bounds: tuple,
    lumped_elements: list[LumpedElementType],
    boundary_types: tuple[tuple[str, str], tuple[str, str], tuple[str, str]],
    cached_corners_and_convexity: list[CornersAndConvexity] | None = None,
    cached_merged_geos: list[tuple[Any, Shapely]] | None = None,
) -> list[StructureType]:
    """Internal mesh override structures. So far, internal override structures are generated by
    `layer_refinement_specs` and lumped element.

    Parameters
    ----------
    structures : list[Structure]
        List of structures, with the simulation structure being the first item.
    wavelength : PositiveFloat
        Wavelength to use for minimal step size in vaccum.
    lumped_elements : List[LumpedElementType]
        List of lumped elements.
    boundary_types : tuple[tuple[str, str], tuple[str, str], tuple[str, str]]
        Boundary type of the simulation domain.
    cached_corners_and_convexity : Optional[list[CornersAndConvexity]]
        Cached corners and convexity data.
    cached_merged_geos : Optional[list[list[tuple[Any, Shapely]]]]
        Cached merged geometries for each layer. If None, will be computed.
    sim_bounds : tuple
        Bounds of the simulation domain excluding the PML regions.

    Returns
    -------
    list[StructureType]
        List of override structures.
    """

    # no need to generate anything if autogrid is not used
    if not self.auto_grid_used:
        return []

    override_structures = []
    # 1) from layer refinement spec
    if self.layer_refinement_used:
        for ind, layer_spec in enumerate(self.layer_refinement_specs):
            if cached_corners_and_convexity is not None:
                cached_data = cached_corners_and_convexity[ind]
            else:
                cached_data = None
            if cached_merged_geos is not None:
                cached_merged = cached_merged_geos[ind]
            else:
                cached_merged = None
            # use simulation size derived from bounds for vacuum dl
            sim_size_local = tuple(bmax - bmin for bmin, bmax in zip(*sim_bounds))
            override_structures += layer_spec.generate_override_structures(
                self._min_vacuum_dl_in_autogrid(wavelength, sim_size_local),
                list(structures),
                sim_bounds,
                boundary_types,
                cached_data,
                cached_merged,
            )
    # 2) from lumped element
    for lumped_element in lumped_elements:
        override_structures += lumped_element.to_mesh_overrides()
    return override_structures


def all_override_structures(
    self: GridSpec,
    structures: list[Structure],
    wavelength: PositiveFloat,
    lumped_elements: list[LumpedElementType],
    boundary_types: tuple[tuple[str, str], tuple[str, str], tuple[str, str]],
    sim_bounds: tuple,
    structure_priority_mode: PriorityMode = "equal",
    internal_override_structures: list[MeshOverrideStructure] | None = None,
) -> list[StructureType]:
    """Internal and external mesh override structures sorted based on their priority. By default,
    the priority of internal override structures is -1, and 0 for external ones.

    Parameters
    ----------
    structures : list[Structure]
        List of structures, with the simulation structure being the first item.
    wavelength : PositiveFloat
        Wavelength to use for minimal step size in vaccum.
    lumped_elements : List[LumpedElementType]
        List of lumped elements.
    sim_bounds : tuple
        Bounds of the simulation domain excluding the PML regions.
    boundary_types : tuple[tuple[str, str], tuple[str, str], tuple[str, str]]
        Boundary type of the simulation domain.
    structure_priority_mode : PriorityMode
        Structure priority setting.
    internal_override_structures : list[MeshOverrideStructure]
        If `None`, recomputes internal override structures.
    Returns
    -------
    list[StructureType]
        List of sorted override structures.
    """

    if internal_override_structures is None:
        internal_override_structures = self.internal_override_structures(
            structures,
            wavelength,
            sim_bounds,
            lumped_elements,
            boundary_types,
        )
    all_structures = internal_override_structures + self.external_override_structures
    return Structure._sort_structures(all_structures, structure_priority_mode)


def _get_all_structures_affecting_grid(
    self: GridSpec,
    structures: list[Structure],
    wavelength: PositiveFloat,
    lumped_elements: list[LumpedElementType],
    boundary_types: tuple[tuple[str, str], tuple[str, str], tuple[str, str]],
    sim_bounds: tuple,
    structure_priority_mode: PriorityMode = "equal",
    internal_override_structures: list[MeshOverrideStructure] | None = None,
) -> list[StructureType]:
    """Get all structures including original structures and all override structures.

    Parameters
    ----------
    structures : List[Structure]
        List of structures, with the simulation structure being the first item.
    wavelength : PositiveFloat
        Wavelength to use for minimal step size in vacuum.
    lumped_elements : List[LumpedElementType]
        List of lumped elements.
    boundary_types : tuple[tuple[str, str], tuple[str, str], tuple[str, str]]
        Boundary type of the simulation domain.
    sim_bounds : tuple
        Bounds of the simulation domain excluding the PML regions.
    structure_priority_mode : PriorityMode
        Structure priority setting.
    internal_override_structures : List[MeshOverrideStructure]
        If `None`, recomputes internal override structures.

    Returns
    -------
    List[StructureType]
        List of all structures including original structures and override structures.
    """
    return list(structures) + self.all_override_structures(
        list(structures),
        wavelength,
        lumped_elements,
        boundary_types,
        sim_bounds,
        structure_priority_mode,
        internal_override_structures,
    )
