"""Compatibility shim for :mod:`tidy3d._common.constants`."""

# ruff: noqa: F401 - ignore unused imports, imports ensure compatibility

# marked as migrated to _common
from __future__ import annotations

from tidy3d._common.constants import (
    ACCELERATION,
    AMP,
    C_0,
    CMCUBE,
    CONDUCTIVITY,
    CURRENT_DENSITY,
    DENSITY,
    DYNAMIC_VISCOSITY,
    ELECTRON_VOLT,
    EPSILON_0,
    ETA_0,
    FARAD,
    GLANCING_CUTOFF,
    GRAV_ACC,
    HBAR,
    HEAT_FLUX,
    HEAT_TRANSFER_COEFF,
    HENRY,
    HERTZ,
    K_B,
    KELVIN,
    LARGE_NUMBER,
    LARGEST_FP_NUMBER,
    M_E_C_SQUARE,
    M_E_EV,
    METER,
    MICROMETER,
    MU_0,
    NANOMETER,
    NEPERPERMETER,
    OHM,
    PERCMCUBE,
    PERMETER,
    PERMITTIVITY,
    PICOSECOND,
    PICOSECOND_PER_NANOMETER_PER_KILOMETER,
    PML_SIGMA,
    RADIAN,
    RADPERMETER,
    RADPERSEC,
    SECOND,
    SPECIFIC_HEAT,
    SPECIFIC_HEAT_CAPACITY,
    TERAHERTZ,
    THERMAL_CONDUCTIVITY,
    THERMAL_EXPANSIVITY,
    VELOCITY_SI,
    VOLT,
    VOLUMETRIC_HEAT_RATE,
    WATT,
    Q_e,
    UnitScaling,
    dp_eps,
    fp_eps,
    inf,
    pec_val,
)
