"""Compatibility shim for :mod:`tidy3d._common.components.types.base`."""

# ruff: noqa: F401 - ignore unused imports, imports ensure compatibility

# marked as migrated to _common
from __future__ import annotations

from tidy3d._common.components.types.base import (
    TYPE_TAG_STR,
    ArrayComplex,
    ArrayComplex1D,
    ArrayComplex2D,
    ArrayComplex3D,
    ArrayComplex4D,
    ArrayConstraints,
    ArrayFloat,
    ArrayFloat1D,
    ArrayFloat2D,
    ArrayFloat3D,
    ArrayFloat4D,
    ArrayInt1D,
    ArrayLike,
    ArrayLikeStrict,
    AuxField,
    Ax,
    Axis,
    Axis2D,
    Bound,
    BoxSurface,
    ClipOperationType,
    ColormapType,
    Complex,
    Coordinate,
    Coordinate2D,
    CoordinateOptional,
    Direction,
    DTypeLike,
    EMField,
    EpsSpecType,
    FieldType,
    FieldVal,
    FreqArray,
    FreqBound,
    FreqBoundMax,
    FreqBoundMin,
    GridSize,
    InterpMethod,
    LengthUnit,
    LumpDistType,
    MatrixReal4x4,
    ModeClassification,
    ModeSolverType,
    ObsGridArray,
    PermittivityComponent,
    PlanePosition,
    PlotScale,
    PlotVal,
    Polarization,
    PolarizationBasis,
    PoleAndResidue,
    PolesAndResidues,
    PriorityMode,
    RealFieldVal,
    ScalarSymmetry,
    Shapely,
    Size,
    Size1D,
    Symmetry,
    TensorReal,
    TrackFreq,
    Undefined,
    UnitsZBF,
    _auto_serializer,
    _coerce,
    _dtype2python,
    _from_complex_dict,
    _list_to_tuple,
    _parse_complex,
    array_alias,
    discriminated_union,
    xyz,
)
