"""Limits and warning thresholds for FDTD simulations."""

from __future__ import annotations

from tidy3d.constants import inf

MIN_GRIDS_PER_WVL = 6.0
MAX_NUM_SOURCES = 1000
MAX_DIFFRACTION_ORDER_GRID_SIZE = 100_000_000
MAX_TIME_STEPS = 1e7
WARN_TIME_STEPS = 1e6
MAX_GRID_CELLS = 20e9
MAX_CELLS_TIMES_STEPS = 1e16
WARN_SIM_DOMAIN_CELLS_EXCLUDING_PML = 100
MAX_TIME_MONITOR_STEPS = 5000
WARN_MONITOR_DATA_SIZE_GB = 10
MAX_MONITOR_INTERNAL_DATA_SIZE_GB = 50
MAX_SIMULATION_DATA_SIZE_GB = 50
WARN_MODE_NUM_CELLS = 1e5
MIN_MONITOR_FREQUENCY_RANGE_PARAMETER = 0.1
MAX_MONITOR_FREQUENCY_RANGE_PARAMETER = 10
NUM_CELLS_WARN_EPSILON = 100_000_000
NUM_STRUCTURES_WARN_EPSILON = 10_000
PML_HEIGHT_FOR_0_DIMS = inf
FIXED_ANGLE_DT_SAFETY_FACTOR = 0.9
RF_FREQ_WARNING = 300e9
MODAL_PEC_FRAME_NAME_PREFIX = "__tidy3d_modal_pec_frame_"
THIN_LENS_SOURCE_SETUP_EVALUATIONS = 4
THIN_LENS_MONITOR_SETUP_EVALUATIONS = 2
THIN_LENS_FIELD_COMPONENTS = 6
MULTIMODE_MODE_ABC_NORMAL_CLEARANCE_CELLS = 2
