name: "tidy3d-frontend-tests"

on:
  workflow_dispatch:
  push:
    branches: [ develop, latest ]
  pull_request:
    branches:
      - latest
      - develop
      - 'pre/*'

jobs:
  build:
    name: Python ${{ matrix.python-version }} - ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
        platform: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        shell: bash
    env:  # Set environment variables for the whole job
      PIP_ONLY_BINARY: gdstk
      MPLBACKEND: agg

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    #----------------------------------------------
    # cache poetry installation
    #----------------------------------------------
    - name: Cache poetry installation
      id: poetry-tool-cache
      uses: actions/cache@v4
      with:
        path: ~/.local
        key: ${{ runner.os }}-poetry-tool-${{ matrix.python-version }}

    #----------------------------------------------
    # install & configure poetry
    #----------------------------------------------
    - name: Install Poetry
      if: steps.poetry-tool-cache.outputs.cache-hit != 'true'
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install "poetry==1.8.2"
        poetry config virtualenvs.in-project true

    #----------------------------------------------
    # cache poetry dependencies
    #----------------------------------------------
    - name: Cache poetry dependencies
      id: poetry-cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          .venv
        key: ${{ runner.os }}-poetry-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-${{ matrix.python-version }}-

    #----------------------------------------------
    # install root project, if required
    #----------------------------------------------
    - name: Install library
      run: |
        poetry --version
        poetry env use python
        poetry env info
        poetry run pip install --upgrade pip wheel setuptools
        poetry run pip install gdstk --only-binary gdstk
        if [ ! -d .venv ] || [ "${{ steps.poetry-cache.outputs.cache-hit }}" != 'true' ]; then
          poetry install -E dev
        else
          poetry install --only-root -E dev
        fi

    #----------------------------------------------
    # run test suite
    #----------------------------------------------
    - name: Run tests
      run: |
        poetry run ruff format . --check --diff
        poetry run ruff check tidy3d --fix --exit-non-zero-on-fix
        poetry run pytest -rA tests
        poetry run pytest -rA tests/_test_data/_test_datasets_no_vtk.py
