name: test-develop-cli

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches:
      - develop
      - 'pre/*' # We should reduce the frequency of these builds to save resources since it tests the docs build which is pretty long.

jobs:
  test-dev-commands:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2
      with:
        version: 1.7.1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: "poetry"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Ubuntu install Pandoc
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install pandoc

    - name: MacOS install Pandoc
      if: matrix.os == 'macos-latest'
      run: brew install pandoc

    - name: Windows install Pandoc
      if: matrix.os == 'windows-latest'
      run: choco install pandoc

    - name: Verify existing installations
      run: |
        python3 --version
        pipx --version

    - name: Run install-dev-environment command
      run: |
        # Unsure if this is a valid command since it just guarantees things run on previous dependencies installation
        # TODO finish debugging installation without previous installation. Tricky on GH Actions on its own since it's interactive.
        poetry run tidy3d develop install-dev-environment

    - name: Run development test commands
      run: |
        poetry run pytest tests/test_cli/full_test_develop.py
        
        
