name: update-lockfile-PR

on:
  workflow_dispatch:
    inputs:
      run-workflow:
        description: 'Set to true to update the lock file and create a PR'
        required: true
        type: boolean
        default: true

  workflow_call:
    inputs:
      run-workflow:
        description: 'Set to true to update the lock file and create a PR'
        required: true
        type: boolean
        default: true

jobs:
  update-lockfile:
    if: github.event.inputs.run-workflow || inputs.run-workflow
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      
      - name: Update lock file
        run: poetry update --lock

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): :robot: Daily update `poetry.lock`"
          title: "Update poetry.lock"
          body: |
            This pull request was automatically generated by a GitHub Action.

            It updates the `poetry.lock` file to reflect changes in the pip state, and whether the package is broken by external depedency changes.
          branch: "daily-chore/update-poetry-lock"
          base: "develop"
          delete-branch: true
