name: public/tidy3d/python-client-daily-run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # Runs at 5am UTC

permissions:
  contents: read

jobs:
  update-lockfile:
    uses: ./.github/workflows/tidy3d-python-client-update-lockfile.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      run-workflow: true

  daily-release:
    uses: ./.github/workflows/tidy3d-python-client-release.yml
    permissions:
      contents: write
      pull-requests: write
      security-events: write
      id-token: write
    with:
      release_tag: 'daily-0.0.0'
      release_type: 'draft'
      workflow_control: 'only-tag-tests'
      client_tests: true
      cli_tests: true
      submodule_tests: false
    secrets: inherit # zizmor: ignore[secrets-inherit]
