name: "public/tidy3d/python-client-submodule-tests"

on:
  push:
    branches: [ latest ]
  
  pull_request:
    branches:
      - latest
  
  workflow_dispatch:
    inputs:
      run-workflow:
        required: true
        type: boolean
        default: true
      release_tag:
        description: 'Release Tag (v2.10.0, v2.10.0rc1)'
        required: false
        type: string
        default: ''

  workflow_call:
    inputs:
      run-workflow:
        required: true
        type: boolean
        default: true
      release_tag:
        description: 'Release Tag (v2.10.0, v2.10.0rc1)'
        required: false
        type: string
        default: ''
    outputs:
      workflow_success:
        description: 'Submodule tests workflow success status'
        value: ${{ jobs.test-latest-submodules.result == 'success' }}

permissions:
  contents: read

jobs:
  test-latest-submodules:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release_tag || inputs.release_tag }}
    if: github.event.inputs.run-workflow || inputs.run-workflow
    steps:
      - name: checkout-head
        if: ${{ !env.RELEASE_TAG }}
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
          persist-credentials: true

      - name: checkout-tag
        if: ${{ env.RELEASE_TAG }}
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ env.RELEASE_TAG }}
          submodules: 'recursive'
          fetch-depth: 0
          persist-credentials: true

      - name: initialize-submodules
        run: |
          git submodule update --init --recursive

      - name: Check submodules for multiple branches
        shell: bash
        run: |
          BRANCHES=("develop" $LATEST_BRANCH) # Add your branches here
          
          for BRANCH in "${BRANCHES[@]}"; do
            echo "Analyzing branch: $BRANCH"
          
            # Fetch all branches and tags
            git fetch --all --verbose
          
            # Checkout the branch
            git checkout $BRANCH
          
            NOTEBOOKS_PATH=docs/notebooks
            FAQ_PATH=docs/faq
          
            # Checking Notebooks submodule
            echo "Checking $NOTEBOOKS_PATH for updates..."
            cd $NOTEBOOKS_PATH
            NOTEBOOKS_CURRENT_COMMIT=$(git rev-parse HEAD)
            echo $(git fetch --all --verbose)
            echo $(git remote get-url origin)
            if git show-ref --verify refs/remotes/origin/$BRANCH; then
              echo "Branch $BRANCH exists."
            else
              echo "::error::Branch $BRANCH does not exist on remote."
              exit 1
            fi
            NOTEBOOKS_LATEST_COMMIT=$(git rev-parse refs/remotes/origin/${BRANCH})
            echo "NOTEBOOKS_LATEST_COMMIT: $NOTEBOOKS_LATEST_COMMIT"
            echo "NOTEBOOKS_CURRENT_COMMIT: $NOTEBOOKS_CURRENT_COMMIT"
          
            cd ../..
            if [ "$NOTEBOOKS_LATEST_COMMIT" != "$NOTEBOOKS_CURRENT_COMMIT" ]; then
              echo "::error::Submodule $NOTEBOOKS_PATH is not up to date with the $BRANCH branch. Please update it."
              exit 1
            else
              echo "Submodule $NOTEBOOKS_PATH is up to date with the $BRANCH branch."
            fi
          
            # Checking FAQs only on the develop branch
            if [[ "$BRANCH" == "develop" ]]; then
              echo "Checking $FAQ_PATH for updates..."
              cd $FAQ_PATH
              FAQ_CURRENT_COMMIT=$(git rev-parse HEAD)
              echo $(git fetch --all --verbose)
              echo $(git remote get-url origin)
              FAQ_LATEST_COMMIT=$(git rev-parse refs/remotes/origin/develop)
              echo "FAQ_LATEST_COMMIT: $FAQ_LATEST_COMMIT"
              echo "FAQ_CURRENT_COMMIT: $FAQ_CURRENT_COMMIT"
              cd ../..
              if [ "$FAQ_LATEST_COMMIT" != "$FAQ_CURRENT_COMMIT" ]; then
                echo "::error::Submodule $FAQ_PATH is not up to date. Please update it."
                exit 1
              else
                echo "Submodule $FAQ_PATH is up to date."
              fi
            fi
          done
